"""empty message

Revision ID: 415aba235ab2
Revises: 21b18aaaf7b5
Create Date: 2023-04-28 21:15:25.295001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '415aba235ab2'
down_revision = '21b18aaaf7b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reply_comment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply_comment',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comment_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reply_to_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], name='reply_comment_ibfk_1'),
    sa.ForeignKeyConstraint(['reply_to_id'], ['reply_comment.id'], name='reply_comment_ibfk_3'),
    sa.ForeignKeyConstraint(['user_id'], ['user_model.id'], name='reply_comment_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
