"""empty message

Revision ID: 6ebadfb804cf
Revises: a128fdfc7118
Create Date: 2023-04-14 11:01:31.078623

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ebadfb804cf'
down_revision = 'a128fdfc7118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('count', sa.Integer(), nullable=False))
        batch_op.drop_column('view_count')
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('view_count', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('count')
        batch_op.drop_column('title')
        batch_op.drop_column('file')

    # ### end Alembic commands ###
