"""empty message

Revision ID: 811d8166b492
Revises: 610769b6c80d
Create Date: 2023-04-15 19:47:05.431554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '811d8166b492'
down_revision = '610769b6c80d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_model', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
