"""empty message

Revision ID: af2bb7d927e5
Revises: 6ebadfb804cf
Create Date: 2023-04-14 11:27:35.562274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af2bb7d927e5'
down_revision = '6ebadfb804cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', mysql.TEXT(), nullable=False))

    # ### end Alembic commands ###
